In [1]:
import numpy as np

In [2]:
arr = [1, 2, 3, 4, 5]
type(arr)

list

In [10]:
arr = np.array(arr) # changes the data type from list to np array
print(type(np.array(arr))) # class "np.ndarray"

<class 'numpy.ndarray'>


In [9]:
isinstance(arr, np.ndarray)

True

In [11]:
print(arr.shape)
print(arr.dtype)
print(arr.ndim)

(5,)
int32
1


In [22]:
# create a 2-dimensional array
b = np.array([
    [7, 3, 3, 3, 2], 
    [8, 3, 2, 2, 8]
])

print(b)
print()
# print the props of b
print(b.shape)
print(b.dtype)
print(b.ndim)

[[7 3 3 3 2]
 [8 3 2 2 8]]

(2, 5)
int32
2


In [34]:
# some inbuilt functions that can be used to initialise numpy arrays 

c = np.random.random((3, 5)) # a function to create a numpy array of random numbers with dimension (3, 5)
c

zeros = np.zeros((3, 6)) # a (3, 6) array of zeros
zeros

ones = np.ones((3, 6)) # a (3, 6) array of ones
ones

identity = np.identity(3) # the identity array creator function
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Inter-operability of arrays with scalars

In [39]:
d = np.array([
    [88, 3, 5, 2], 
    [8, 2, 7, 9]
])

e = np.array([
    [7, 80, 3, 5], 
    [9, 3, 6, 2]
])

# performing element-wise operation on d and e 
print(d + e)
print()
print(d * e)
print()
print(5 + e)

[[95 83  8  7]
 [17  5 13 11]]

[[616 240  15  10]
 [ 72   6  42  18]]

[[12 85  8 10]
 [14  8 11  7]]


In [47]:
# array indexing \
f = np.array([
    [77, 3, 4, 6, 7, 8, 9],
    [66, 7, 2, 9, 7, 9, 10],
    [8, 99, 1, 6, 7, 2, 1], 
    [8, 5, 7, 3, 2, 1, 4]
])

print(f.shape)

print()

f[2] # using one index will return all numbers along a dimension
f[3, 5] # using specific index will return a number from a specific position in the array

# array slicing
f[:3, 2:]

# boolean array indexing 
f[f > 15]



(4, 7)



array([77, 66, 99])